version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-2"
    # REACT_APP_API_SERVICE_URL: "http://webapp-alb-23323279.ap-southeast-2.elb.amazonaws.com"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo building prod images...
      - >
        docker build \
          -f services/frontend/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest \
          ./services/frontend

  post_build:
    commands:
      - echo pushing prod images to ecr...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest