service: movie-rating-system

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  profile: ServerlessUser
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
custom:
  tableName: auth

functions:
  signUp:
    handler: src/endpoints/signup.handler
    events:
      - http:
          path: signup
          method: POST
          cors: 
            origin: 'http://frontend-657412319.ap-southeast-2.elb.amazonaws.com'
  login:
    handler: src/endpoints/login.handler
    events:
      - http:
          path: login
          method: POST
          cors: true
  addNewFavourite:
    handler: src/endpoints/add-favourite.handler
    events:
      - http:
          path: add-new-favourite
          method: POST
          cors: true
  getFavourites:
    handler: src/endpoints/get-favourites.handler
    events:
      - http:
          path: get-favourites/{ID}
          method: GET
          cors: true
  authenticate:
    handler: src/endpoints/authenticate.handler
    events:
      - http:
          path: authenticate
          method: GET
          cors: true
